import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { useTranslation } from 'react-i18next';

import LanguageDropdown from '@/layouts/components/LanguageDropdown';
import { useSettings } from '@/hooks/useSetting';
import ModeToggler from '@/layouts/components/ModeToggler';
// import useFetch from '@/hooks/useFetch';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });
// interface Menus {
//   label: string;
//   key: string;
// }
export default function Home() {
  // const { data: menus } = useFetch<Menus[]>('/api/get-menus');
  const { settings, saveSettings } = useSettings();
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          <LanguageDropdown settings={settings} saveSettings={saveSettings} />
          <ModeToggler settings={settings} saveSettings={saveSettings} />
        </p>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('Docs')} <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('Learn')} <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('Templates')} <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {t('Deploy')} <span>-&gt;</span>
            </h2>
          </a>
        </div>
      </main>
    </>
  );
}
