# workflow名称
name: demo
# 对应第1步，master代码变动执行该workflow
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest
    steps:
      - name: Server Reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/projects/test
            source ~/.bashrc
            export NVM_DIR="$HOME/.nvm"
            nvm use 18
